name = "maya-dev-ui"
main = "worker.js"
compatibility_date = "2024-11-01"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "replace-with-auth-kv-id"

[[kv_namespaces]]
binding = "ANALYTICS_CACHE"
id = "replace-with-analytics-kv-id"

[[unsafe.bindings]]
type = "ratelimit"
name = "MY_RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 10, period = 60 }
